# Generated by Django 6.1.1 on 2026-09-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offeringdiscount_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeringdiscount',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offeringdiscount',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
